name: Update README Date

on:
  schedule:
    - cron: '0 0 * * *' # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update date in README.md
        run: |
          # Lấy ngày hiện tại theo định dạng DD/MM/YYYY
          CURRENT_DATE=$(date +'%d/%m/%Y')
          # Dùng # làm dấu phân cách thay vì /
          sed -i "s#Ngày cập nhật: .*#Ngày cập nhật: $CURRENT_DATE#" README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update date in README.md to $CURRENT_DATE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
